name: ClaudiaMcKenzieDesigns
favicon: null
layout_spectrum: 0.99903
typography_spectrum: 0.98989
title: Claudia McKenzie Designs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1a18'
    - '#d3d1cd'
    - '#000000'
    - '#403e3e'
    - '#74655e'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.7070043403655291
purpose: []
