name: Claudia McKenzie
favicon: null
layout_spectrum: 0.34906
typography_spectrum: 0.9072
title: Claudia McKenzie Designs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff3f6'
    - '#13161e'
    - '#9aa8b7'
    - '#5b6c83'
    - '#cccdc8'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
