name: ClaudiaMcKenzieDesigns
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2a2c3b'
    - '#a8aeba'
    - '#957f5a'
    - '#7f4b1b'
  brandStrength: 0.24964307737536728
  lightness: 0.7523525187280029
  saturation: 0.758478102972731
  rhythmicContrast: 0.7070043403655291
purpose: []
