name: ClaudiaMcKenzieDesigns
favicon: null
layout_spectrum: 0.26864522229880095
typography_spectrum: 0.6962401100900024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.24964307737536728
  lightness: 0.7523525187280029
  saturation: 0.758478102972731
  rhythmicContrast: 0.7070043403655291
purpose: []
