name: ClaudiaMcKenzieDesigns
favicon: null
layout_spectrum: 0.26864522229880095
typography_spectrum: 0.6962401100900024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2c2c2'
    - '#6a959c'
    - '#265662'
    - '#1a1613'
    - '#332f2c'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.7070043403655291
purpose: []
